# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'guieditrooms.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_EditRoomWindow(object):
    def setupUi(self, EditRoomWindow):
        EditRoomWindow.setObjectName("EditRoomWindow")
        EditRoomWindow.resize(508, 547)
        self.centralwidget = QtWidgets.QWidget(EditRoomWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.groupBox = QtWidgets.QGroupBox(self.frame)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.RmWin_RoomTable = QtWidgets.QTableWidget(self.groupBox)
        self.RmWin_RoomTable.setObjectName("RmWin_RoomTable")
        self.RmWin_RoomTable.setColumnCount(2)
        self.RmWin_RoomTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.RmWin_RoomTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.RmWin_RoomTable.setHorizontalHeaderItem(1, item)
        self.RmWin_RoomTable.horizontalHeader().setDefaultSectionSize(200)
        self.gridLayout_5.addWidget(self.RmWin_RoomTable, 1, 0, 1, 1)
        self.frame_4 = QtWidgets.QFrame(self.groupBox)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.RmWin_AddButton = QtWidgets.QPushButton(self.frame_4)
        self.RmWin_AddButton.setObjectName("RmWin_AddButton")
        self.gridLayout_4.addWidget(self.RmWin_AddButton, 0, 0, 1, 1)
        self.RmWin_RemoveButton = QtWidgets.QPushButton(self.frame_4)
        self.RmWin_RemoveButton.setObjectName("RmWin_RemoveButton")
        self.gridLayout_4.addWidget(self.RmWin_RemoveButton, 0, 1, 1, 1)
        self.gridLayout_5.addWidget(self.frame_4, 0, 0, 1, 1)
        self.gridLayout_6.addWidget(self.groupBox, 0, 0, 1, 1)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.RmWin_FinishButton = QtWidgets.QPushButton(self.frame_3)
        self.RmWin_FinishButton.setObjectName("RmWin_FinishButton")
        self.gridLayout_3.addWidget(self.RmWin_FinishButton, 0, 0, 1, 1)
        self.RmWin_CancelButton = QtWidgets.QPushButton(self.frame_3)
        self.RmWin_CancelButton.setObjectName("RmWin_CancelButton")
        self.gridLayout_3.addWidget(self.RmWin_CancelButton, 0, 1, 1, 1)
        self.gridLayout_6.addWidget(self.frame_3, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        EditRoomWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(EditRoomWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 508, 21))
        self.menubar.setObjectName("menubar")
        EditRoomWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(EditRoomWindow)
        self.statusbar.setObjectName("statusbar")
        EditRoomWindow.setStatusBar(self.statusbar)

        self.retranslateUi(EditRoomWindow)
        QtCore.QMetaObject.connectSlotsByName(EditRoomWindow)

    def retranslateUi(self, EditRoomWindow):
        _translate = QtCore.QCoreApplication.translate
        EditRoomWindow.setWindowTitle(_translate("EditRoomWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("EditRoomWindow", "Rooms"))
        item = self.RmWin_RoomTable.horizontalHeaderItem(0)
        item.setText(_translate("EditRoomWindow", "Availability"))
        item = self.RmWin_RoomTable.horizontalHeaderItem(1)
        item.setText(_translate("EditRoomWindow", "Rooms"))
        self.RmWin_AddButton.setText(_translate("EditRoomWindow", "Add"))
        self.RmWin_RemoveButton.setText(_translate("EditRoomWindow", "Remove"))
        self.RmWin_FinishButton.setText(_translate("EditRoomWindow", "Finish"))
        self.RmWin_CancelButton.setText(_translate("EditRoomWindow", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    EditRoomWindow = QtWidgets.QMainWindow()
    ui = Ui_EditRoomWindow()
    ui.setupUi(EditRoomWindow)
    EditRoomWindow.show()
    sys.exit(app.exec_())
