# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'guieditbuildings.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_EditBuildingWindow(object):
    def setupUi(self, EditBuildingWindow):
        EditBuildingWindow.setObjectName("EditBuildingWindow")
        EditBuildingWindow.resize(508, 547)
        self.centralwidget = QtWidgets.QWidget(EditBuildingWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.BldWin_BuildingNameLineEdit = QtWidgets.QLineEdit(self.frame_2)
        self.BldWin_BuildingNameLineEdit.setObjectName("BldWin_BuildingNameLineEdit")
        self.gridLayout_2.addWidget(self.BldWin_BuildingNameLineEdit, 0, 1, 1, 1)
        self.gridLayout_6.addWidget(self.frame_2, 0, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.frame)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.frame_4 = QtWidgets.QFrame(self.groupBox)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.BldWin_AddButton = QtWidgets.QPushButton(self.frame_4)
        self.BldWin_AddButton.setObjectName("BldWin_AddButton")
        self.gridLayout_4.addWidget(self.BldWin_AddButton, 0, 0, 1, 1)
        self.BldWin_RemoveButton = QtWidgets.QPushButton(self.frame_4)
        self.BldWin_RemoveButton.setObjectName("BldWin_RemoveButton")
        self.gridLayout_4.addWidget(self.BldWin_RemoveButton, 0, 1, 1, 1)
        self.gridLayout_5.addWidget(self.frame_4, 0, 0, 1, 1)
        self.BldWin_FloorTable = QtWidgets.QTableWidget(self.groupBox)
        self.BldWin_FloorTable.setObjectName("BldWin_FloorTable")
        self.BldWin_FloorTable.setColumnCount(1)
        self.BldWin_FloorTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.BldWin_FloorTable.setHorizontalHeaderItem(0, item)
        self.BldWin_FloorTable.horizontalHeader().setDefaultSectionSize(450)
        self.gridLayout_5.addWidget(self.BldWin_FloorTable, 1, 0, 1, 1)
        self.gridLayout_6.addWidget(self.groupBox, 1, 0, 1, 1)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.BldWin_FinishButton = QtWidgets.QPushButton(self.frame_3)
        self.BldWin_FinishButton.setObjectName("BldWin_FinishButton")
        self.gridLayout_3.addWidget(self.BldWin_FinishButton, 0, 0, 1, 1)
        self.BldWin_CancelButton = QtWidgets.QPushButton(self.frame_3)
        self.BldWin_CancelButton.setObjectName("BldWin_CancelButton")
        self.gridLayout_3.addWidget(self.BldWin_CancelButton, 0, 1, 1, 1)
        self.gridLayout_6.addWidget(self.frame_3, 2, 0, 1, 1)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        EditBuildingWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(EditBuildingWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 508, 21))
        self.menubar.setObjectName("menubar")
        EditBuildingWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(EditBuildingWindow)
        self.statusbar.setObjectName("statusbar")
        EditBuildingWindow.setStatusBar(self.statusbar)

        self.retranslateUi(EditBuildingWindow)
        QtCore.QMetaObject.connectSlotsByName(EditBuildingWindow)

    def retranslateUi(self, EditBuildingWindow):
        _translate = QtCore.QCoreApplication.translate
        EditBuildingWindow.setWindowTitle(_translate("EditBuildingWindow", "MainWindow"))
        self.label.setText(_translate("EditBuildingWindow", "Building Name"))
        self.groupBox.setTitle(_translate("EditBuildingWindow", "Floors"))
        self.BldWin_AddButton.setText(_translate("EditBuildingWindow", "Add"))
        self.BldWin_RemoveButton.setText(_translate("EditBuildingWindow", "Remove"))
        item = self.BldWin_FloorTable.horizontalHeaderItem(0)
        item.setText(_translate("EditBuildingWindow", "Floors"))
        self.BldWin_FinishButton.setText(_translate("EditBuildingWindow", "Finish"))
        self.BldWin_CancelButton.setText(_translate("EditBuildingWindow", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    EditBuildingWindow = QtWidgets.QMainWindow()
    ui = Ui_EditBuildingWindow()
    ui.setupUi(EditBuildingWindow)
    EditBuildingWindow.show()
    sys.exit(app.exec_())
